//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReleaseManagementAssignmentProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class DevModule
    {
        public int DevModuleid { get; set; }
        public Nullable<int> pid { get; set; }
        public string Modulename { get; set; }
        public Nullable<int> devstatus { get; set; }
        public Nullable<int> devid { get; set; }
        public Nullable<int> mid { get; set; }
        public Nullable<int> teamleadid { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> ExpectedDate { get; set; }
    
        public virtual Developer Developer { get; set; }
        public virtual Manager Manager { get; set; }
        public virtual project project { get; set; }
        public virtual TeamLead TeamLead { get; set; }
    }
}
